name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.576787e9-74fe-4a66-bd6f-f4586bd7a698}}
          heroku_app_name: "github-cd-koby"
          heroku_email: "kobysillito@gmail.com"